### ISSUE TITLE
withtraceback -> with_traceback

### ISSUE THREAD

**Issue by DMLooter** [Madison-Esports-Club/UWVerifierBot#7]
The withtraceback() method we use in our logging of errors does not exist and needs to be removed. We should also raise any uncaught errors.

**Comment by DMLooter** [comment]
any of the else cases where we have `print("{command name} error:", error, error.withtraceback())` should become:

`print("{command name} error:", error)
raise error`

**Comment by antgurevich** [comment]
@DMLooter Raising the error would crash the bot, is there a reason we want to be doing this?

**Comment by DMLooter** [comment]
In this case any non-explicitly caught exceptions means code errors, so honestly it should raise hell. But it also doesn't fully crash the bot when raised within the explicit error handler. I believe the module has a handler above that that prints the stack trace and allows the bot to continue.

**Comment by DMLooter** [comment]
Also events.py is going away. it was only for my testing with making discord events and does not work with pycord.

**Comment by antgurevich** [comment]
So do we want the file just deleted then or should we keep it for now? It's the only place traceback is used

**Comment by DMLooter** [comment]
oh shit I guess I was just doing something dumb while making that then. We can just delete that file.
